project_name: cosi-server

before:
    hooks:
        - go mod tidy
        - ./build_lint.sh

builds:
    -
        main: main.go

        binary: sbin/cosi-serverd

        env:
            - CGO_ENABLED=0

        flags: -tags dev

        goos:
            - linux
            - darwin
            - windows
            - freebsd
            - solaris
            - illumos

        goarch:
            - amd64

        ignore:
            -
                goarch: 386

        ldflags:
            - -X github.com/circonus-labs/cosi-server/internal/release.VERSION={{.Version}} 
            - -X github.com/circonus-labs/cosi-server/internal/release.COMMIT={{.ShortCommit}} 
            - -X github.com/circonus-labs/cosi-server/internal/release.DATE={{.Date}} 
            - -X github.com/circonus-labs/cosi-server/internal/release.TAG={{.Tag}}


archives:
    -
        id: default
        name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"

        format: tar.gz

        replacements:
            amd64: x86_64

        format_overrides:
            -
                goos: windows
                format: zip

        files:
            - LICENSE
            - README.md
            - CHANGELOG.md
            - etc/example-*
            - service/*
            - content/**/*

release:
    github:
        owner: circonus-labs
        name: cosi-server

    prerelease: false
    draft: false
    name_template: "{{.ProjectName}}-v{{.Version}}"

changelog:
    filters:
        exclude:
            - '^doc:'
            - typo
    sort: asc

snapshot:
    name_template: SNAPSHOT-{{.Commit}}

checksum:
    name_template: "{{.ProjectName}}_checksums.txt"
