project_name: cosi-server

builds:
    -
        main: main.go

        binary: sbin/cosi-serverd

        env:
            - CGO_ENABLED=0

        flags: -tags dev

        goos:
            - linux
            - darwin
            - windows
            - freebsd
            - solaris

        goarch:
            - amd64

        ignore:
            -
                goarch: 386

        ldflags: -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.tag={{.Tag}}

archive:
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"

    format: tar.gz

    replacements:
        amd64: 64-bit
        darwin: macOS

    format_overrides:
        -
            goos: windows
            format: zip

    files:
        - LICENSE
        - README.md
        - CHANGELOG.md
        - etc/example-*
        - service/*
        - content/**/*

release:
    github:
        owner: circonus-labs
        name: cosi-server

    prerelease: true
    draft: false
    name_template: "{{.ProjectName}}-v{{.Version}}"

changelog:
    filters:
        exclude:
            - '^doc:'
            - typo
    sort: asc

snapshot:
    name_template: SNAPSHOT-{{.Commit}}

checksum:
    name_template: "{{.ProjectName}}_checksums.txt"
