type = "check"
name = "group"
version = "1.0.0"

description = '''
Group check configuration template.

Used by agent's statsd interface to aggregate a set of metrics across multiple systems.
'''

# NOTE: for checks, configs do not actually support multiple items - cosi register
# will only use the *first* one in the configs array, after toml parsing, when
# it creates the check.
[configs.group]
template = '''
{
    "brokers": [],
    "config": {},
    "display_name": "{{.GroupID}} cosi/group",
    "metric_limit": 0,
    "metrics": [],
    "notes": null,
    "period": 60,
    "status": "active",
    "tags": [],
    "target": "group:{{.GroupID}}",
    "timeout": 10,
    "type": null
}
'''
