type = "graph"
name = "df"
version = "1.0.0"

description = '''
Percent of space and inodes used per filesystem
'''

variable = true

[filters]
include = []
exclude = [
    "^/boot$",
    "^/dev$"
]

[configs.pct_used]
variable = true
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [],
    "description": "% space and inodes used per filesystem",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": "100",
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": null,
    "style": "area",
    "tags": [],
    "title": "{{.HostName}} {{.Item}} %Used"
}
'''
datapoints = [
{
    variable = false,
    metric_regex = "df`([^`]+)`pct_used",
    template = '''
    {
        "alpha": "0.3",
        "axis": "l",
        "check_id": {{.CheckID}},
        "color": "#4fa18e",
        "data_formula": null,
        "derive": "gauge",
        "hidden": false,
        "legend_formula": null,
        "metric_name": "{{.MetricName}}",
        "metric_type": "numeric",
        "name": "% Space Used",
        "stack": null
    }
    '''
},
{
    variable = false,
    metric_regex = "df`([^`]+)`pct_inode_used",
    template = '''
    {
        "alpha": "0.3",
        "axis": "l",
        "check_id": {{.CheckID}},
        "color": "#657aa6",
        "data_formula": null,
        "derive": "gauge",
        "hidden": false,
        "legend_formula": null,
        "metric_name": "{{.MetricName}}",
        "metric_type": "numeric",
        "name": "% Inode Used",
        "stack": null
    }
    '''
}
]
