type = "graph"
name = "diskstats"
version = "1.0.0"

description = '''
Disk Utilization Summary
'''

variable = true

[filters]
exclude = [
    "^loop[0-9]+$",
    "^sr[0-9]+$",
    "^fd[0-9]+$"
]
include = []

[configs.utilization]
variable = false
template = '''
{
    "access_keys": [],
    "composites": [],
    "description": "",
    "datapoints": [],
    "guides": [],
    "line_style": "interpolated",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": "100",
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": null,
    "style": "area",
    "tags": [ "use", "use:disk-utilization" ],
    "title": "{{.HostName}} Disk Utilization"
}
'''
datapoints = [
{
    variable = true,
    metric_regex = "^diskstats`([^`]+)`io_ms$",
    template = '''
    {
        "alpha": "0.3",
        "axis": "l",
        "check_id": {{.CheckID}},
        "color": "#657aa6",
        "data_formula": "=VAL/10",
        "derive": "counter",
        "hidden": false,
        "legend_formula": "=round(auto(VAL),2)",
        "metric_name": "{{.MetricName}}",
        "metric_type": "numeric",
        "name": "{{.MetricName}}",
        "stack": null
    }
    '''
}
]

[configs.saturation]
variable = false
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [],
    "description": "",
    "guides": [],
    "line_style": "interpolated",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": null,
    "style": "area",
    "tags": [ "use", "use:disk-saturation" ],
    "title": "{{.HostName}} Disk Saturation"
}
'''
datapoints = [
{
    variable = true,
    metric_regex = "^diskstats`([^`]+)`io_ms_weighted$",
    template = '''
    {
        "alpha": "0.3",
        "axis": "l",
        "check_id": {{.CheckID}},
        "color": "#7B4D94",
        "data_formula": "=VAL/10",
        "derive": "counter",
        "hidden": false,
        "legend_formula": "=round(auto(VAL),2)",
        "metric_name": "{{.MetricName}}",
        "metric_type": "numeric",
        "name": "{{.Item}} average queue size, computed",
        "stack": null
    }
    '''
}
]
