type = "graph"
name = "cassandra_info"
version = "1.0.0"

description = '''
Cassandra global stats
'''

[configs.heap_usage]
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [
        {
            "alpha": "0.3",
            "axis": "l",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#4fa18e",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`heap_mem_used",
            "metric_type": "numeric",
            "name": "heap used",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "l",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#657aa6",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`heap_mem_max",
            "metric_type": "numeric",
            "name": "heap max",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "l",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#b5c52d",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`off_heap_mem_used",
            "metric_type": "numeric",
            "name": "off heap used",
            "stack": null
        }
    ],
    "description": "Cassandra heap usage stats",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": null,
    "style": "area",
    "tags": ["database:cassandra", "cassandra:heap"],
    "title": "{{.HostName}} Cassandra heap stats"
}
'''

[configs.key_cache]
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [
        {
            "alpha": "0.3",
            "axis": "l",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#4fa18e",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`key_cache_entries",
            "metric_type": "numeric",
            "name": "key cache entries",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "r",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#657aa6",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`key_cache_capacity",
            "metric_type": "numeric",
            "name": "key cache capacity",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "r",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#b5c52d",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`key_cache_size",
            "metric_type": "numeric",
            "name": "key cache size",
            "stack": null
        }
    ],
    "description": "Cassandra key cache",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": null,
    "style": "area",
    "tags": ["database:cassandra", "cassandra:key_cache"],
    "title": "{{.HostName}} Cassandra key cache"
}
'''

[configs.counter_cache]
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [
        {
            "alpha": "0.3",
            "axis": "l",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#4fa18e",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`counter_cache_entries",
            "metric_type": "numeric",
            "name": "counter cache entries",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "r",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#657aa6",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`counter_cache_capacity",
            "metric_type": "numeric",
            "name": "counter cache capacity",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "r",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#b5c52d",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`counter_cache_size",
            "metric_type": "numeric",
            "name": "counter cache size",
            "stack": null
        }
    ],
    "description": "Cassandra counter cache",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": null,
    "style": "area",
    "tags": ["database:cassandra", "cassandra:counter_cache"],
    "title": "{{.HostName}} Cassandra counter cache"
}
'''

[configs.chunk_cache]
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [
        {
            "alpha": "0.3",
            "axis": "l",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#4fa18e",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`chunk_cache_entries",
            "metric_type": "numeric",
            "name": "chunk cache entries",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "r",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#657aa6",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`chunk_cache_capacity",
            "metric_type": "numeric",
            "name": "chunk cache capacity",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "r",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#b5c52d",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`chunk_cache_size",
            "metric_type": "numeric",
            "name": "chunk cache size",
            "stack": null
        }
    ],
    "description": "Cassandra chunk cache",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": null,
    "style": "area",
    "tags": ["database:cassandra", "cassandra:chunk_cache"],
    "title": "{{.HostName}} Cassandra chunk cache"
}
'''

[configs.info]
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [
        {
            "alpha": "0.3",
            "axis": "l",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#4fa18e",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`generation_number",
            "metric_type": "numeric",
            "name": "generation number",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "r",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#657aa6",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_info`uptime_secs",
            "metric_type": "numeric",
            "name": "uptime seconds",
            "stack": null
        }
    ],
    "description": "Cassandra info",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": null,
    "style": "area",
    "tags": ["database:cassandra", "cassandra:generation"],
    "title": "{{.HostName}} Cassandra info"
}
'''

[configs.cluster_key_cache]
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [
        {
            "alpha": "0.3",
            "axis": "l",
            "caql": "search:metric(\"(metric:cassandra_info`key_cache_entries) (metric_tags:{{.ClusterTag}})\") | window:mean(60)",
            "check_id": {{.CheckID}},
            "color": "#4fa18e",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": null,
            "metric_type": "caql",
            "name": "Average key cache enteries",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "r",
            "caql": "search:metric(\"(metric:cassandra_info`key_cache_size) (metric_tags:{{.ClusterTag}})\") | window:mean(60)",
            "check_id": {{.CheckID}},
            "color": "#657aa6",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": null,
            "metric_type": "caql",
            "name": "Average key cache size",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "r",
            "caql": "search:metric(\"(metric:cassandra_info`key_cache_capacity) (metric_tags:{{.ClusterTag}})\") | window:mean(60)",
            "check_id": {{.CheckID}},
            "color": "#b5c52d",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": null,
            "metric_type": "caql",
            "name": "Average key cache capacity",
            "stack": null
        }
    ],
    "description": "Cassandra cluster key cache",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": "Cluster graph",
    "style": "area",
    "tags": ["database:cassandra", "cassandra:cluster_key_cache"],
    "title": "{{.ClusterName}} Cassandra key cache"
}
'''

[configs.cluster_counter_cache]
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [
        {
            "alpha": "0.3",
            "axis": "l",
            "caql": "search:metric(\"(metric:cassandra_info`counter_cache_entries) (metric_tags:{{.ClusterTag}})\") | window:mean(60)",
            "check_id": {{.CheckID}},
            "color": "#4fa18e",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": null,
            "metric_type": "caql",
            "name": "Average counter cache enteries",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "r",
            "caql": "search:metric(\"(metric:cassandra_info`counter_cache_size) (metric_tags:{{.ClusterTag}})\") | window:mean(60)",
            "check_id": {{.CheckID}},
            "color": "#657aa6",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": null,
            "metric_type": "caql",
            "name": "Average counter cache size",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "r",
            "caql": "search:metric(\"(metric:cassandra_info`counter_cache_capacity) (metric_tags:{{.ClusterTag}})\") | window:mean(60)",
            "check_id": {{.CheckID}},
            "color": "#b5c52d",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": null,
            "metric_type": "caql",
            "name": "Average counter cache capacity",
            "stack": null
        }
    ],
    "description": "Cassandra cluster counter cache",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": "Cluster graph",
    "style": "area",
    "tags": ["database:cassandra", "cassandra:cluster_counter_cache"],
    "title": "{{.ClusterName}} Cassandra counter cache"
}
'''

[configs.cluster_counter_cache_hit_pct]
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [
        {
            "alpha": "0.3",
            "axis": "l",
            "caql": "search:metric(\"(metric:cassandra_info`counter_cache_hit_pct) (metric_tags:{{.ClusterTag}})\")",
            "check_id": {{.CheckID}},
            "color": "#4fa18e",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": null,
            "metric_type": "caql",
            "name": "Counter cache hit %",
            "stack": null
        }
    ],
    "description": "Cassandra cluster counter cache hit %",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": "Cluster graph",
    "style": "area",
    "tags": ["database:cassandra", "cassandra:cluster_counter_cache_hit_pct"],
    "title": "{{.ClusterName}} Cassandra counter cache hit %"
}
'''

[configs.cluster_chunk_cache]
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [
        {
            "alpha": "0.3",
            "axis": "l",
            "caql": "search:metric(\"(metric:cassandra_info`chunk_cache_entries) (metric_tags:{{.ClusterTag}})\") | window:mean(60)",
            "check_id": {{.CheckID}},
            "color": "#4fa18e",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": null,
            "metric_type": "caql",
            "name": "Average chunk cache enteries",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "r",
            "caql": "search:metric(\"(metric:cassandra_info`chunk_cache_size) (metric_tags:{{.ClusterTag}})\") | window:mean(60)",
            "check_id": {{.CheckID}},
            "color": "#657aa6",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": null,
            "metric_type": "caql",
            "name": "Average chunk cache size",
            "stack": null
        },
        {
            "alpha": "0.3",
            "axis": "r",
            "caql": "search:metric(\"(metric:cassandra_info`chunk_cache_capacity) (metric_tags:{{.ClusterTag}})\") | window:mean(60)",
            "check_id": {{.CheckID}},
            "color": "#b5c52d",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": null,
            "metric_type": "caql",
            "name": "Average chunk cache capacity",
            "stack": null
        }
    ],
    "description": "Cassandra cluster chunk cache",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": "Cluster graph",
    "style": "area",
    "tags": ["database:cassandra", "cassandra:cluster_chunk_cache"],
    "title": "{{.ClusterName}} Cassandra chunk cache"
}
'''

[configs.cluster_chunk_cache_hit_pct]
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [
        {
            "alpha": "0.3",
            "axis": "l",
            "caql": "search:metric(\"(metric:cassandra_info`chunk_cache_hit_pct) (metric_tags:{{.ClusterTag}})\")",
            "check_id": {{.CheckID}},
            "color": "#4fa18e",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": null,
            "metric_type": "caql",
            "name": "Chunk cache hit %",
            "stack": null
        }
    ],
    "description": "Cassandra cluster chunk cache hit %",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": "Cluster graph",
    "style": "area",
    "tags": ["database:cassandra", "cassandra:cluster_chunk_cache_hit_pct"],
    "title": "{{.ClusterName}} Cassandra chunk cache hit %"
}
'''
