type = "graph"
name = "cassandra_compaction"
version = "1.0.0"

description = '''
Cassandra compaction stats
'''

[configs.compaction]
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [
        {
            "alpha": "0.3",
            "axis": "l",
            "caql": null,
            "check_id": {{.CheckID}},
            "color": "#4fa18e",
            "data_formula": null,
            "derive": false,
            "hidden": false,
            "legend_formula": null,
            "metric_name": "cassandra_compaction`pending_tasks",
            "metric_type": "numeric",
            "name": "pending compaction tasks",
            "stack": null
        }
    ],
    "description": "Cassandra pending compaction tasks",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": null,
    "style": "area",
    "tags": ["database:cassandra", "cassandra:compaction"],
    "title": "{{.HostName}} cassandra compaction stats"
}
'''
