type = "graph"
name = "pg_db_size"
version = "1.0.0"

description = '''
Postgres Database size
'''

variable = true
[filters]
include = ["postgres"]
exclude = []

[configs.db_size]
variable = true
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [],
    "description": "Postgres {{.Item}} database size",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": null,
    "style": "line",
    "tags": ["database:postgres", "database:size"],
    "title": "{{.HostName}} {{.Item}} Postgres Database Size"
}
'''
datapoints = [
{
    variable = false,
    metric_regex = "pg_db_size`([^`]+)",
    template = '''
    {
        "alpha": null,
        "axis": "l",
        "check_id": {{.CheckID}},
        "color": "#af5779",
        "data_formula": null,
        "derive": "gauge",
        "hidden": false,
        "legend_formula": null,
        "metric_name": "{{.MetricName}}",
        "metric_type": "numeric",
        "name": "db size",
        "stack": null
    }
    '''
},
{
    variable = false,
    template = '''
    {
        "alpha": null,
        "axis": "l",
        "caql" : "metric:average(\"{{.CheckUUID}}\",\"pg_db_size`{{.Item}}\") | forecasting:dewma(0.2, 0.001, fill=2)",
        "check_id": {{.CheckID}},
        "color": "#4fa18e",
        "data_formula": null,
        "derive": false,
        "hidden": false,
        "legend_formula": null,
        "metric_name": null,
        "metric_type": "caql",
        "name": "db size forecast",
        "stack": null
    }
    '''
}
]
