type = "graph"
name = "pg_cache"
version = "1.0.0"

description = '''
Postgres Cache hits vs. filesystem hits
'''

variable = true

[configs.cache]
variable = true
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [],
    "description": "Postgres {{.Item}} cache info",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": null,
    "style": "line",
    "tags": ["database:postgres", "database:cache"],
    "title": "{{.HostName}} {{.Item}} Postgres Cache"
}
'''
datapoints = [
{
    variable = false,
    metric_regex = "pg_cache`([^`]+)`disk_bytes_read",
    template = '''
    {
        "alpha": "0.80",
        "axis": "l",
        "check_id": {{.CheckID}},
        "color": "#a0505c",
        "data_formula": null,
        "derive": "derive",
        "hidden": false,
        "legend_formula": null,
        "metric_name": "{{.MetricName}}",
        "metric_type": "numeric",
        "name": "disk bytes read rate of change",
        "stack": null
    }
    '''
},
{
    variable = false,
    metric_regex = "pg_cache`([^`]+)`cache_bytes_read",
    template = '''
    {
        "alpha": null,
        "axis": "l",
        "check_id": {{.CheckID}},
        "color": "#2dc43c",
        "data_formula": null,
        "derive": "derive",
        "hidden": false,
        "legend_formula": null,
        "metric_name": "{{.MetricName}}",
        "metric_type": "numeric",
        "name": "cache bytes read rate of change",
        "stack": null
    }
    '''
}
]
