type = "graph"
name = "disk"
version = "1.0.0"

description = '''
Disk IO number of read/write and bytes read/written
'''

variable = true

[filters]
exclude = []
include = [
    "^sd[a-z]$",
    "^xvd[a-z]$",
    "^ad[a-z][0-9]+$",
    "^da[0-9]+$"
]

[configs.io]
variable = true
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [],
    "description": "Disk IO number of read/write and bytes read/written.",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": null,
    "style": "area",
    "tags": [],
    "title": "{{.HostName}} {{.Item}} Disk IO"
}
'''
datapoints = [
{
    variable = false,
    metric_regex = "disk`([^`]+)`reads",
    template = '''
    {
        "alpha": "0.3",
        "axis": "l",
        "check_id": null,
        "color": "#4fa18e",
        "data_formula": null,
        "derive": "counter",
        "hidden": false,
        "legend_formula": "=round(VAL,2)",
        "metric_name": "{{.MetricName}}",
        "metric_type": "numeric",
        "name": "Reads",
        "stack": null
    }
    '''
},
{
    variable = false,
    metric_regex = "disk`([^`]+)`writes",
    template = '''
    {
        "alpha": "0.3",
        "axis": "l",
        "check_id": null,
        "color": "#657aa6",
        "data_formula": "=-1 * VAL",
        "derive": "counter",
        "hidden": false,
        "legend_formula": "=round(VAL,2)",
        "metric_name": "{{.MetricName}}",
        "metric_type": "numeric",
        "name": "Writes",
        "stack": null
    }
    '''
},
{
    variable = false,
    metric_regex = "disk`([^`]+)`nread",
    template = '''
    {
        "alpha": "0.3",
        "axis": "r",
        "check_id": null,
        "color": "#b5c52d",
        "data_formula": null,
        "derive": "counter",
        "hidden": false,
        "legend_formula": "=round(auto(VAL),2)",
        "metric_name": "{{.MetricName}}",
        "metric_type": "numeric",
        "name": "Bytes read",
        "stack": null
    }
    '''
},
{
    variable = false,
    metric_regex = "disk`([^`]+)`nwritten",
    template = '''
    {
        "alpha": "0.3",
        "axis": "r",
        "check_id": null,
        "color": "#8e69a2",
        "data_formula": "=-1 * VAL",
        "derive": "counter",
        "hidden": false,
        "legend_formula": "=round(auto(VAL),2)",
        "metric_name": "{{.MetricName}}",
        "metric_type": "numeric",
        "name": "Bytes written",
        "stack": null
    }
    '''
}
]
