type = "graph"
name = "pg_connections"
version = "1.0.0"

description = '''
Postgres max and current connection tracker
'''

[configs.connections]
template = '''
{
    "access_keys": [],
    "composites": [],
    "datapoints": [
        {
            "alpha": null,
            "axis": "l",
            "check_id": {{.CheckID}},
            "color": "#af5779",
            "data_formula": null,
            "derive": "gauge",
            "hidden": false,
            "legend_formula": null,
            "metric_name": "pg_connections`max_connections",
            "metric_type": "numeric",
            "name": "max",
            "stack": null
        },
        {
            "alpha": null,
            "axis": "l",
            "check_id": {{.CheckID}},
            "color": "#4fa18e",
            "data_formula": null,
            "derive": "gauge",
            "hidden": false,
            "legend_formula": null,
            "metric_name": "pg_connections`active",
            "metric_type": "numeric",
            "name": "Active",
            "stack": null
        }
    ],
    "description": "Postgres connections",
    "guides": [],
    "line_style": "stepped",
    "logarithmic_left_y": null,
    "logarithmic_right_y": null,
    "max_left_y": null,
    "max_right_y": null,
    "metric_clusters": [],
    "min_left_y": null,
    "min_right_y": null,
    "notes": null,
    "style": "line",
    "tags": ["database:postgres", "database:connections"],
    "title": "{{.HostName}} Postgres Connections"
}
'''
